using System.Collections.Generic;
using Plugin.Iconize;

namespace SepsisTrust.IconFonts
{
    public static class MedicalFontCollection
    {
        /// <summary>
        /// Gets the icons.
        /// </summary>
        /// <value>
        /// The icons.
        /// </value>
        public static IList<IIcon> Icons { get; } = new List<IIcon>();

        static MedicalFontCollection( )
        {
            Icons.Add("medical-accessibility", '\ue900');
            Icons.Add("medical-administration", '\ue901');
            Icons.Add("medical-alternative-complementary", '\ue902');
            Icons.Add("medical-ambulance", '\ue903');
            Icons.Add("medical-anesthesia", '\ue904');
            Icons.Add("medical-billing", '\ue905');
            Icons.Add("medical-cardiology", '\ue906');
            Icons.Add("medical-care-staff-area", '\ue907');
            Icons.Add("medical-cath-lab", '\ue908');
            Icons.Add("medical-chapel", '\ue909');
            Icons.Add("medical-coffee-shop", '\ue90a');
            Icons.Add("medical-dental", '\ue90b');
            Icons.Add("medical-dermatology", '\ue90c');
            Icons.Add("medical-diabetes-education", '\ue90d');
            Icons.Add("medical-drinking-fountain", '\ue90e');
            Icons.Add("medical-ear-nose-throat", '\ue90f');
            Icons.Add("medical-elevators", '\ue910');
            Icons.Add("medical-emergency", '\ue911');
            Icons.Add("medical-family-practice", '\ue912');
            Icons.Add("medical-fire-extinguisher", '\ue913');
            Icons.Add("medical-first-aid", '\ue914');
            Icons.Add("medical-genetics", '\ue915');
            Icons.Add("medical-gift-shop", '\ue916');
            Icons.Add("medical-health-education", '\ue917');
            Icons.Add("medical-health-services", '\ue918');
            Icons.Add("medical-hearing-assistance", '\ue919');
            Icons.Add("medical-hospital", '\ue91a');
            Icons.Add("medical-i-accessibility", '\ue91b');
            Icons.Add("medical-i-administration", '\ue91c');
            Icons.Add("medical-i-alternative-complementary", '\ue91d');
            Icons.Add("medical-i-ambulance", '\ue91e');
            Icons.Add("medical-i-anesthesia", '\ue91f');
            Icons.Add("medical-i-billing", '\ue920');
            Icons.Add("medical-i-cardiology", '\ue921');
            Icons.Add("medical-i-care-staff-area", '\ue922');
            Icons.Add("medical-i-cath-lab", '\ue923');
            Icons.Add("medical-i-chapel", '\ue924');
            Icons.Add("medical-i-coffee-shop", '\ue925');
            Icons.Add("medical-i-dental", '\ue926');
            Icons.Add("medical-i-dermatology", '\ue927');
            Icons.Add("medical-i-diabetes-education", '\ue928');
            Icons.Add("medical-i-drinking-fountain", '\ue929');
            Icons.Add("medical-i-ear-nose-throat", '\ue92a');
            Icons.Add("medical-i-elevators", '\ue92b');
            Icons.Add("medical-i-emergency", '\ue92c');
            Icons.Add("medical-i-family-practice", '\ue92d');
            Icons.Add("medical-i-fire-extinguisher", '\ue92e');
            Icons.Add("medical-i-first-aid", '\ue92f');
            Icons.Add("medical-i-genetics", '\ue930');
            Icons.Add("medical-i-gift-shop", '\ue931');
            Icons.Add("medical-i-health-education", '\ue932');
            Icons.Add("medical-i-health-services", '\ue933');
            Icons.Add("medical-i-hearing-assistance", '\ue934');
            Icons.Add("medical-i-hospital", '\ue935');
            Icons.Add("medical-i-imaging-alternative-ct", '\ue936');
            Icons.Add("medical-i-imaging-alternative-mri", '\ue937');
            Icons.Add("medical-i-imaging-alternative-mri-two", '\ue938');
            Icons.Add("medical-i-imaging-alternative-pet", '\ue939');
            Icons.Add("medical-i-imaging-root-category", '\ue93a');
            Icons.Add("medical-i-immunizations", '\ue93b');
            Icons.Add("medical-i-infectious-diseases", '\ue93c');
            Icons.Add("medical-i-information-us", '\ue93d');
            Icons.Add("medical-i-inpatient", '\ue93e');
            Icons.Add("medical-i-intensive-care", '\ue93f');
            Icons.Add("medical-i-internal-medicine", '\ue940');
            Icons.Add("medical-i-interpreter-services", '\ue941');
            Icons.Add("medical-i-kidney", '\ue942');
            Icons.Add("medical-i-laboratory", '\ue943');
            Icons.Add("medical-i-labor-delivery", '\ue944');
            Icons.Add("medical-imaging-alternative-ct", '\ue945');
            Icons.Add("medical-imaging-alternative-mri", '\ue946');
            Icons.Add("medical-imaging-alternative-mri-two", '\ue947');
            Icons.Add("medical-imaging-alternative-pet", '\ue948');
            Icons.Add("medical-imaging-root-category", '\ue949');
            Icons.Add("medical-i-mammography", '\ue94a');
            Icons.Add("medical-i-medical-library", '\ue94b');
            Icons.Add("medical-i-medical-records", '\ue94c');
            Icons.Add("medical-i-mental-health", '\ue94d');
            Icons.Add("medical-immunizations", '\ue94e');
            Icons.Add("medical-i-mri-pet", '\ue94f');
            Icons.Add("medical-i-neurology", '\ue950');
            Icons.Add("medical-infectious-diseases", '\ue951');
            Icons.Add("medical-information-us", '\ue952');
            Icons.Add("medical-i-no-smoking", '\ue953');
            Icons.Add("medical-inpatient", '\ue954');
            Icons.Add("medical-intensive-care", '\ue955');
            Icons.Add("medical-internal-medicine", '\ue956');
            Icons.Add("medical-interpreter-services", '\ue957');
            Icons.Add("medical-i-nursery", '\ue958');
            Icons.Add("medical-i-nutrition", '\ue959');
            Icons.Add("medical-i-oncology", '\ue95a');
            Icons.Add("medical-i-ophthalmology", '\ue95b');
            Icons.Add("medical-i-outpatient", '\ue95c');
            Icons.Add("medical-i-pathology", '\ue95d');
            Icons.Add("medical-i-pediatrics", '\ue95e');
            Icons.Add("medical-i-pharmacy", '\ue95f');
            Icons.Add("medical-i-physical-therapy", '\ue960');
            Icons.Add("medical-i-radiology", '\ue961');
            Icons.Add("medical-i-registration", '\ue962');
            Icons.Add("medical-i-respiratory", '\ue963');
            Icons.Add("medical-i-restaurant", '\ue964');
            Icons.Add("medical-i-restrooms", '\ue965');
            Icons.Add("medical-i-smoking", '\ue966');
            Icons.Add("medical-i-social-services", '\ue967');
            Icons.Add("medical-i-stairs", '\ue968');
            Icons.Add("medical-i-surgery", '\ue969');
            Icons.Add("medical-i-text-telephone", '\ue96a');
            Icons.Add("medical-i-ultrasound", '\ue96b');
            Icons.Add("medical-i-volume-control", '\ue96c');
            Icons.Add("medical-i-waiting-area", '\ue96d');
            Icons.Add("medical-i-womens-health", '\ue96e');
            Icons.Add("medical-kidney", '\ue96f');
            Icons.Add("medical-laboratory", '\ue970');
            Icons.Add("medical-labor-delivery", '\ue971');
            Icons.Add("medical-mammography", '\ue972');
            Icons.Add("medical-medical-library", '\ue973');
            Icons.Add("medical-medical-records", '\ue974');
            Icons.Add("medical-mental-health", '\ue975');
            Icons.Add("medical-mri-pet", '\ue976');
            Icons.Add("medical-neurology", '\ue977');
            Icons.Add("medical-no-smoking", '\ue978');
            Icons.Add("medical-nursery", '\ue979');
            Icons.Add("medical-nutrition", '\ue97a');
            Icons.Add("medical-oncology", '\ue97b');
            Icons.Add("medical-ophthalmology", '\ue97c');
            Icons.Add("medical-outpatient", '\ue97d');
            Icons.Add("medical-pathology", '\ue97e');
            Icons.Add("medical-pediatrics", '\ue97f');
            Icons.Add("medical-pharmacy", '\ue980');
            Icons.Add("medical-physical-therapy", '\ue981');
            Icons.Add("medical-radiology", '\ue982');
            Icons.Add("medical-registration", '\ue983');
            Icons.Add("medical-respiratory", '\ue984');
            Icons.Add("medical-restaurant", '\ue985');
            Icons.Add("medical-restrooms", '\ue986');
            Icons.Add("medical-smoking", '\ue987');
            Icons.Add("medical-social-services", '\ue988');
            Icons.Add("medical-stairs", '\ue989');
            Icons.Add("medical-surgery", '\ue98a');
            Icons.Add("medical-text-telephone", '\ue98b');
            Icons.Add("medical-ultrasound", '\ue98c');
            Icons.Add("medical-volume-control", '\ue98d');
            Icons.Add("medical-waiting-area", '\ue98e');
            Icons.Add("medical-womens-health", '\ue98f');

        }
    }
}